In [1]:
import pandas as pd 
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.metrics import root_mean_squared_error

In [2]:
df=pd.read_csv("C:/Artificial/New folder/StudentStudyHour1.csv")
df.head()

   Hours  Scores
0    2.5    21.0
1    5.1    47.0
2    3.2    27.0
3    8.5    75.0
4    3.5    30.0

In [3]:
df.isnull().sum()

Hours     0
Scores    2
dtype: int64

In [4]:
df.shape

(28, 2)

In [5]:
df=df.dropna()

In [6]:
y=df['Scores']
x=df.drop('Scores',axis=1)

In [7]:
x

    Hours
0     2.5
1     5.1
2     3.2
3     8.5
4     3.5
5     1.5
6     9.2
7     5.5
9     2.7
10    7.7
11    5.9
12    4.5
13    3.3
14    1.1
15    8.9
17    1.9
18    6.1
19    7.4
20    2.7
21    4.8
22    3.8
23    6.9
24    7.8
25    1.3
26    2.6
27    6.1

In [8]:
y

0     21.0
1     47.0
2     27.0
3     75.0
4     30.0
5     20.0
6     88.0
7     60.0
9     25.0
10    85.0
11    62.0
12    41.0
13    42.0
14    17.0
15    95.0
17    24.0
18    67.0
19    69.0
20    30.0
21    54.0
22    35.0
23    76.0
24    86.0
25    19.0
26    30.0
27    63.0
Name: Scores, dtype: float64

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [10]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((18, 1), (8, 1), (18,), (8,))

In [11]:
lr=LinearRegression()
model=lr.fit(x_train,y_train)

In [12]:
y_pred=model.predict(x_test)
df=pd.DataFrame({'y_test':y_test,'y_pred':y_pred})

In [15]:
print("mean_squared_error:",mean_squared_error(y_test,y_pred))
print("root_mean_squared_error:",root_mean_squared_error(y_test,y_pred))
print("r2_score:",r2_score(y_test,y_pred))

mean_squared_error: 29.13458764727173
root_mean_squared_error: 5.3976464915064355
r2_score: 0.9416998527522311